"""
report.py

Builds the PDF summary of a collection run.

Each error event in the table links to its own extracted .txt file (relative
path within the output folder), so clicking a row in the PDF opens exactly
that error in the system text editor. Notepad has no jump-to-line option;
one-file-per-error honors the intent instead of fighting the tool.
"""

from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from .collector import CollectionSummary

ACCENT = colors.HexColor("#1F4E5F")


def build_pdf(summary: CollectionSummary, output_path: Path) -> Path:
    """Writes the summary PDF and returns its path."""
    styles = getSampleStyleSheet()
    body = styles["BodyText"]
    link_style = ParagraphStyle(
        "EventLink", parent=body, textColor=colors.HexColor("#0B5394"), fontSize=9
    )
    cell = ParagraphStyle("Cell", parent=body, fontSize=9, leading=11)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        title=f"Pothos report — {summary.executable}",
        leftMargin=0.7 * inch,
        rightMargin=0.7 * inch,
    )

    story = [
        Paragraph(f"Pothos Diagnostic Report — {summary.executable}", styles["Title"]),
        Paragraph(
            f"Window: last {summary.hours:g} hours &nbsp;·&nbsp; "
            f"Collected: {summary.collected_at.strftime('%Y-%m-%d %H:%M:%S')} &nbsp;·&nbsp; "
            f"{len(summary.event_files)} event(s), {len(summary.dump_files)} crash artifact(s)",
            body,
        ),
        Spacer(1, 12),
    ]

    story.extend(_event_section(summary, cell, link_style, styles))
    story.extend(_dump_section(summary, cell, styles))

    story.append(Spacer(1, 18))
    story.append(Paragraph(
        "Generated by Pothos. Event links open the extracted per-event text "
        "files in the events/ folder beside this PDF.",
        ParagraphStyle("Footer", parent=body, fontSize=8, textColor=colors.grey),
    ))

    doc.build(story)
    return output_path


def _event_section(summary, cell, link_style, styles):
    yield Paragraph("Error & Warning Events", styles["Heading2"])

    if not summary.event_files:
        yield Paragraph("No matching events found in the selected window.", cell)
        return

    header = [
        Paragraph("<b>Time</b>", cell),
        Paragraph("<b>ID</b>", cell),
        Paragraph("<b>Level</b>", cell),
        Paragraph("<b>Summary</b>", cell),
        Paragraph("<b>Details</b>", cell),
    ]
    rows = [header]

    for event, relative_path in summary.event_files:
        first_line = event.message.splitlines()[0] if event.message else "(no message)"
        if len(first_line) > 110:
            first_line = first_line[:107] + "..."
        rows.append([
            Paragraph(event.time_created.strftime("%m-%d %H:%M:%S"), cell),
            Paragraph(str(event.event_id), cell),
            Paragraph(event.level_name, cell),
            Paragraph(_escape(first_line), cell),
            Paragraph(
                f'<link href="{relative_path.as_posix()}">open</link>', link_style
            ),
        ])

    table = Table(rows, colWidths=[1.0 * inch, 0.55 * inch, 0.7 * inch, 3.75 * inch, 0.6 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#D9E4E8")),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F7F8")]),
    ]))
    yield table


def _dump_section(summary, cell, styles):
    yield Spacer(1, 14)
    yield Paragraph("Crash Artifacts", styles["Heading2"])

    if not summary.dump_files:
        yield Paragraph("No crash dumps or WER reports found for this window.", cell)
        return

    for relative_path in summary.dump_files:
        yield Paragraph(
            f'• <link href="{relative_path.as_posix()}" color="#0B5394">'
            f"{_escape(relative_path.name)}</link>",
            cell,
        )


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
